/**
 * Additional environment variable typings that are not auto-generated by
 * `wrangler types`. These are merged with the global `Env` interface from
 * env.d.ts via TypeScript declaration merging.
 */
interface Env {
  /** Cloudflare Zero Trust Access team domain, e.g. `https://<team>.cloudflareaccess.com` */
  CF_ACCESS_TEAM_DOMAIN?: string;
  /** Cloudflare Zero Trust Access Application Audience (AUD) tag */
  CF_ACCESS_POLICY_AUD?: string;
}
